# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calc.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 475)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 400, 100))
        self.label.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"font: 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.Btn_zero = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_zero.setGeometry(QtCore.QRect(0, 400, 150, 75))
        self.Btn_zero.setStyleSheet("")
        self.Btn_zero.setObjectName("Btn_zero")
        self.Btn_equal = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_equal.setGeometry(QtCore.QRect(150, 400, 150, 75))
        self.Btn_equal.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.Btn_equal.setObjectName("Btn_equal")
        self.Btn_7 = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_7.setGeometry(QtCore.QRect(0, 100, 100, 100))
        self.Btn_7.setObjectName("Btn_7")
        self.Btn_9 = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_9.setGeometry(QtCore.QRect(200, 100, 100, 100))
        self.Btn_9.setObjectName("Btn_9")
        self.Btn_8 = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_8.setGeometry(QtCore.QRect(100, 100, 100, 100))
        self.Btn_8.setObjectName("Btn_8")
        self.Btn_4 = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_4.setGeometry(QtCore.QRect(0, 200, 100, 100))
        self.Btn_4.setObjectName("Btn_4")
        self.Btn_6 = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_6.setGeometry(QtCore.QRect(200, 200, 100, 100))
        self.Btn_6.setObjectName("Btn_6")
        self.Btn_5 = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_5.setGeometry(QtCore.QRect(100, 200, 100, 100))
        self.Btn_5.setObjectName("Btn_5")
        self.Btn_3 = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_3.setGeometry(QtCore.QRect(200, 300, 100, 100))
        self.Btn_3.setObjectName("Btn_3")
        self.Btn_2 = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_2.setGeometry(QtCore.QRect(100, 300, 100, 100))
        self.Btn_2.setObjectName("Btn_2")
        self.Btn_1 = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_1.setGeometry(QtCore.QRect(0, 300, 100, 100))
        self.Btn_1.setObjectName("Btn_1")
        self.Btn_plus = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_plus.setGeometry(QtCore.QRect(300, 100, 100, 100))
        self.Btn_plus.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.Btn_plus.setObjectName("Btn_plus")
        self.Btn_minus = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_minus.setGeometry(QtCore.QRect(300, 200, 100, 100))
        self.Btn_minus.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.Btn_minus.setObjectName("Btn_minus")
        self.Btn_mult = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_mult.setGeometry(QtCore.QRect(300, 300, 100, 100))
        self.Btn_mult.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.Btn_mult.setObjectName("Btn_mult")
        self.Btn_divide = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_divide.setGeometry(QtCore.QRect(300, 400, 100, 75))
        self.Btn_divide.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.Btn_divide.setObjectName("Btn_divide")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.add_functions()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Калькулятор"))
        self.Btn_zero.setText(_translate("MainWindow", "0"))
        self.Btn_equal.setText(_translate("MainWindow", "="))
        self.Btn_7.setText(_translate("MainWindow", "7"))
        self.Btn_9.setText(_translate("MainWindow", "9"))
        self.Btn_8.setText(_translate("MainWindow", "8"))
        self.Btn_4.setText(_translate("MainWindow", "4"))
        self.Btn_6.setText(_translate("MainWindow", "6"))
        self.Btn_5.setText(_translate("MainWindow", "5"))
        self.Btn_3.setText(_translate("MainWindow", "3"))
        self.Btn_2.setText(_translate("MainWindow", "2"))
        self.Btn_1.setText(_translate("MainWindow", "1"))
        self.Btn_plus.setText(_translate("MainWindow", "+"))
        self.Btn_minus.setText(_translate("MainWindow", "-"))
        self.Btn_mult.setText(_translate("MainWindow", "*"))
        self.Btn_divide.setText(_translate("MainWindow", "/"))


    def add_functions(self):
        self.Btn_zero.clicked.connect(lambda: self.write_number(self.Btn_zero.text()))
        self.Btn_1.clicked.connect(lambda: self.write_number(self.Btn_1.text()))
        self.Btn_2.clicked.connect(lambda: self.write_number(self.Btn_2.text()))
        self.Btn_3.clicked.connect(lambda: self.write_number(self.Btn_3.text()))
        self.Btn_4.clicked.connect(lambda: self.write_number(self.Btn_4.text()))
        self.Btn_5.clicked.connect(lambda: self.write_number(self.Btn_5.text()))
        self.Btn_6.clicked.connect(lambda: self.write_number(self.Btn_6.text()))
        self.Btn_7.clicked.connect(lambda: self.write_number(self.Btn_7.text()))
        self.Btn_8.clicked.connect(lambda: self.write_number(self.Btn_8.text()))
        self.Btn_9.clicked.connect(lambda: self.write_number(self.Btn_9.text()))
        self.Btn_plus.clicked.connect(lambda: self.write_number(self.Btn_plus.text()))
        self.Btn_minus.clicked.connect(lambda: self.write_number(self.Btn_minus.text()))
        self.Btn_mult.clicked.connect(lambda: self.write_number(self.Btn_mult.text()))
        self.Btn_divide.clicked.connect(lambda: self.write_number(self.Btn_divide.text()))
        self.Btn_equal.clicked.connect(self.result)

    def write_number(self, number):
        self.label.setText(self.label.text() + number)

    def result(self):
        res = eval(self.label.text())
        self.label.setText(str(res))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
